table Ads_Network
	lineageTag: c2d3e4f5-0001-0001-0001-000000000001

	measure 'Network Cost' = SUM('Ads_Network'[Cost])
		formatString: #,0
		lineageTag: c2d3e4f5-0201-0201-0201-000000000201

	measure 'Network Clicks' = SUM('Ads_Network'[Clicks])
		formatString: #,0
		lineageTag: c2d3e4f5-0202-0202-0202-000000000202

	measure 'Network Conversions' = SUM('Ads_Network'[Conversions])
		formatString: #,0.0
		lineageTag: c2d3e4f5-0203-0203-0203-000000000203

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c2d3e4f5-0101-0101-0101-000000000101
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 6a086e97-3088-4a42-8a09-3a6d1f579ac4
			defaultHierarchy: LocalDateTable_e59e5f47-a9c8-4d5f-adba-305b8f04f289.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column Network
		dataType: string
		lineageTag: c2d3e4f5-0102-0102-0102-000000000102
		summarizeBy: none
		sourceColumn: Network

		annotation SummarizationSetBy = Automatic

	column Cost
		dataType: double
		lineageTag: c2d3e4f5-0103-0103-0103-000000000103
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

	column Clicks
		dataType: double
		lineageTag: c2d3e4f5-0104-0104-0104-000000000104
		summarizeBy: sum
		sourceColumn: Clicks

		annotation SummarizationSetBy = Automatic

	column Impressions
		dataType: double
		lineageTag: c2d3e4f5-0105-0105-0105-000000000105
		summarizeBy: sum
		sourceColumn: Impressions

		annotation SummarizationSetBy = Automatic

	column Conversions
		dataType: double
		lineageTag: c2d3e4f5-0107-0107-0107-000000000107
		summarizeBy: sum
		sourceColumn: Conversions

		annotation SummarizationSetBy = Automatic

	column Year_Month
		dataType: string
		lineageTag: c2d3e4f5-0108-0108-0108-000000000108
		summarizeBy: none
		sourceColumn: Year_Month

		annotation SummarizationSetBy = Automatic

	partition Ads_Network = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\ADMIN\Desktop\Code\Báo Cáo Ads\GoogleAds_Ecom2026_20260429.xlsx"), null, true),
				    Sheet = Source{[Item="Daily_Network",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    #"Selected Columns" = Table.SelectColumns(#"Promoted Headers",{"Date","Network","Cost","Clicks","Impressions","Conversions","Year_Month"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Selected Columns",{
				        {"Date", type date},
				        {"Cost", type number},
				        {"Clicks", type number},
				        {"Impressions", type number},
				        {"Conversions", type number}
				    })
				in
				    #"Changed Type"

